MAKE = make
all:
	$(MAKE) -C networkservice/ all
	$(MAKE) -C networkapi/ all
	$(MAKE) -C multitask/ all
	$(MAKE) -C misc/ all
	$(MAKE) -C system/ all
	$(MAKE) -C RandLib/ all
	$(MAKE) -C Demo/ all
	
clean:
	$(MAKE) -C networkservice/ clean
	$(MAKE) -C networkapi/ clean
	$(MAKE) -C multitask/ clean
	$(MAKE) -C misc/ clean
	$(MAKE) -C system/ clean
	$(MAKE) -C RandLib/ clean
	$(MAKE) -C Demo/ clean
